[package]
name = "ray_tracer_challenge"
version = "0.1.0"
authors = ["Laurence Billingham <laurence@travelnest.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
approx = "0.3.2"
